export const ADMIN_PROFILE_REQUEST = 'ADMIN_PROFILE_REQUEST'
export const ADMIN_PROFILE_ERROR = 'ADMIN_PROFILE_ERROR'
export const ADMIN_PROFILE_SUCCESS = 'ADMIN_PROFILE_SUCCESS'
export const HOME_ROUTE_UPDATE = 'HOME_ROUTE_UPDATE'
